# -*- coding: utf-8 -*-
"""Yelp_Hotel_Reviews_Web_Scraper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13awHtJ5dnpdutcAMoxECNnlvbApnoB7z
"""

import bs4
import urllib
import urllib.request as url
import pandas as pd

url_list=[
['https://www.yelp.com/biz/aria-resort-and-casino-las-vegas-8',
 'https://www.yelp.com/biz/aria-resort-and-casino-las-vegas-8?start=20'],

['https://www.yelp.com/biz/four-seasons-hotel-las-vegas-las-vegas',
 'https://www.yelp.com/biz/four-seasons-hotel-las-vegas-las-vegas?start=20'],

['https://www.yelp.com/biz/skylofts-at-mgm-grand-las-vegas-2',
 'https://www.yelp.com/biz/skylofts-at-mgm-grand-las-vegas-2?start=20'],

 ['https://www.yelp.com/biz/encore-las-vegas-2',
  'https://www.yelp.com/biz/encore-las-vegas-2?start=20'],

['https://www.yelp.com/biz/wynn-las-vegas-las-vegas-3',
 'https://www.yelp.com/biz/wynn-las-vegas-las-vegas-3?start=20'],

['https://www.yelp.com/biz/the-venetian-las-vegas-las-vegas-6',
 'https://www.yelp.com/biz/the-venetian-las-vegas-las-vegas-6?start=20'], 

['https://www.yelp.com/biz/the-cosmopolitan-of-las-vegas-las-vegas',
  'https://www.yelp.com/biz/the-cosmopolitan-of-las-vegas-las-vegas?start=20'],

['https://www.yelp.com/biz/the-palazzo-las-vegas-las-vegas-3',
 'https://www.yelp.com/biz/the-palazzo-las-vegas-las-vegas-3?start=20'],

['https://www.yelp.com/biz/bellagio-hotel-las-vegas-6',
 'https://www.yelp.com/biz/bellagio-hotel-las-vegas-6?start=20'],

['https://www.yelp.com/biz/aria-sky-suites-las-vegas-3',
 'https://www.yelp.com/biz/aria-sky-suites-las-vegas-3?start=20'],

['https://www.yelp.com/biz/caesars-palace-las-vegas-10',
 'https://www.yelp.com/biz/caesars-palace-las-vegas-10?start=20'],

['https://www.yelp.com/biz/the-nomad-hotel-las-vegas-las-vegas-3',
 'https://www.yelp.com/biz/the-nomad-hotel-las-vegas-las-vegas-3?start=20'],

['https://www.yelp.com/biz/red-rock-casino-resort-and-spa-las-vegas-7',
 'https://www.yelp.com/biz/red-rock-casino-resort-and-spa-las-vegas-7?start=20'],

['https://www.yelp.com/biz/vdara-hotel-and-spa-las-vegas-3',
 'https://www.yelp.com/biz/vdara-hotel-and-spa-las-vegas-3?start=20'],

['https://www.yelp.com/biz/trump-international-hotel-las-vegas-las-vegas-2',
 'https://www.yelp.com/biz/trump-international-hotel-las-vegas-las-vegas-2?start=20'],

['https://www.yelp.com/biz/mandalay-bay-resort-and-casino-las-vegas-5',
 'https://www.yelp.com/biz/mandalay-bay-resort-and-casino-las-vegas-5?start=20'],

['https://www.yelp.com/biz/waldorf-astoria-las-vegas-las-vegas-2',
 'https://www.yelp.com/biz/waldorf-astoria-las-vegas-las-vegas-2?start=20'],

['https://www.yelp.com/biz/delano-las-vegas-las-vegas-3',
 'https://www.yelp.com/biz/delano-las-vegas-las-vegas-3?start=20'],

['https://www.yelp.com/biz/the-nobu-hotel-las-vegas',
 'https://www.yelp.com/biz/the-nobu-hotel-las-vegas?start=20'],

['https://www.yelp.com/biz/m-resort-spa-casino-henderson-3',
 'https://www.yelp.com/biz/m-resort-spa-casino-henderson-3?start=20']          
]

def ExtractReviews(urllist):

  reviews=[]

  for h in range(len(urllist)):

    opener = url.build_opener()
    opener.addheaders = [('User-agent', 'Mozilla/5.0')]
    
    srclink_hotel = opener.open(urllist[h])
    data_hotel = bs4.BeautifulSoup(srclink_hotel,'html.parser')

    hotel_name = data_hotel.find("h1", {"class": "lemon--h1__373c0__2ZHSL heading--h1__373c0__dvYgw undefined heading--inline__373c0__10ozy"}).string

    review_raw = data_hotel.find_all("span", {"class": "lemon--span__373c0__3997G raw__373c0__3rcx7", "lang": "en"})

    for i in range(len(review_raw)):
      reviews.append(review_raw[i].get_text())

  reviews = list(dict.fromkeys(reviews))
  print("")

  return [['Yelp']*len(reviews), [hotel_name]*len(reviews), reviews]

final_reviews_list = []
final_hotel_name_list = []
final_source_list = []

for l in range(len(url_list)):
  current_url_list = url_list[l]
  output = ExtractReviews(current_url_list)

  final_reviews_list.append(output[2])
  final_hotel_name_list.append(output[1])
  final_source_list.append(output[0])

for i in range(len(final_reviews_list)):
  if len(final_reviews_list[i])>=20:
    final_reviews_list[i] = final_reviews_list[i][:20]
    final_hotel_name_list[i] = final_hotel_name_list[i][:20]
    final_source_list[i] = final_source_list[i][:20]

merged_hotel_list = []
merged_reviews_list = []
merged_source_list = []

for sub in final_hotel_name_list:
  for item in sub:
    merged_hotel_list.append(item)

for sub in final_reviews_list:
  for item in sub:
    merged_reviews_list.append(item)

for sub in final_source_list:
  for item in sub:
    merged_source_list.append(item)

final_df = pd.DataFrame(list(zip(merged_hotel_list, merged_source_list, merged_reviews_list)),columns =['Hotel', 'Source', 'Text'])
final_df.to_csv("yelp_hotel_reviews.csv",index=False)